### ISSUE TITLE
Stream length not reported (and therefore no progress bar shown)

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-cli#10]
I'm sorry, I think I broke things!

The downloading-file stream is not [reporting](https://github.com/TheFox/flickr-cli/blob/2e4c7c673d8f73515bc1010bfb36281689101c40/src/TheFox/FlickrCli/Command/DownloadCommand.php#L389) it's size at all, and so we can't use this to either display a progress bar or (as I was wanting to do) check that any existing file is actually the same size (as a better check than just checking if it exists).

Do you know what is causing this?

Thanks! :-)

**Comment by TheFox** [comment]
I had this issue too. I don't know why it's happening. I'm getting the size on big files (100 MiB).

**Comment by samwilson** [comment]
Hm, okay. Yeah, it's strange. Must be something at Flickr's end?

Well, I might just add in a thing that hides the progress bar if there's no size available (but still shows the download progress and speed). Will send a PR.

Thanks!

**Comment by samwilson** [comment]
Closing in favour of #11.
