### ISSUE TITLE
New command to add md5 checksum machine tags

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-cli#20]
As described in various places ([e.g.](https://longair.net/blog/2009/12/19/hashing-flickr-photos/)) the easiest way to get a checksum of an uploaded file is to add your own md5 tag in the form `checksum:md5=xxxxxx`.

I propose a new command, `checksums` that takes a `--hash` parameter that specifies what hash function to use, and default to `md5`.

What do you think?

The idea is that then any uploading tool can check to see if a file has already been uploaded, and a duplicate-finding tool can find (exact) duplicates very easily.

**Comment by TheFox** [comment]
I would rather use `sha1` as default instead. But this is a good idea.

**Comment by samwilson** [comment]
Yes, sha1 sounds good. Will do.

**Comment by samwilson** [comment]
Okay, I've started work on this in #34. I think it needs some work on the logging and usability perhaps.... let's discuss in that PR though. :-)
