### ISSUE TITLE
Use --verbose standard CLI option, and hide debugging output by default

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-cli#22]
At the moment, debug logs are always output, which is too much information in most cases. I'd like to add a new `--verbose` parameter that can be used to turn on the debug output, and have it turned off by default.

**Comment by TheFox** [comment]
Sounds good.

**Comment by samwilson** [comment]
I just realised that of course there is already a standard option for this:

      -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

We just need to use it. :-)

**Comment by TheFox** [comment]
Ah, yes. I almost forgot this. Of course this would be a better solution. :) 👍

**Comment by TheFox** [comment]
Done.
