### ISSUE TITLE
Make installable as a global Composer package

### ISSUE THREAD

**Issue by samwilson** [TheFox/flickr-cli#23]
I'd like to suggest that the standard (non-development) installation procedure for Flickr CLI should be:

    composer global require --no-dev thefox/flickr-cli

More info: https://getcomposer.org/doc/03-cli.md#global

The main change we'd need to make would be to move `application.php` to `bin/flickr-cli` and add it as a [vendor binary](https://getcomposer.org/doc/articles/vendor-binaries.md).

This would not have to be a  breaking change, as we could still have `application.php`, until the next major version bump.

**Comment by TheFox** [comment]
I would rather also prefer the usage of `bin` directory. This is a more clear way.
